### PR TITLE
Add fish-caller

### PR DESCRIPTION
**Pull request by squaresolid**

### CODE REVIEW

**Comment by kasbah** [comment]
Hey, you are missing a BOM.

**Comment by squaresolid** [comment]
i did, i upload it as .tsv just like the instruction.
i also uploaded .pdf and .ods version

:a

[]
andreas siagian
lifepatch - citizen initiative in art, science and technology
http://lifepatch.org | http://urbancult.net
http://andreassiagian.wordpress.com
+628175471005
[/]

**Comment by kasbah** [comment]
In that case you need to add a [kitnic.yaml](https://github.com/monostable/kitspace#kitnicyaml-format) pointing to the TSV. You can also pick a color and add a link to a site in the yaml. The spaces in the filename may give you some trouble. Use https://kitspace.org/submit to check if it works.

**Comment by squaresolid** [comment]
ok i added kitnic.yaml. is it correct?


[]
andreas siagian
lifepatch - citizen initiative in art, science and technology
http://lifepatch.org | http://urbancult.net
http://andreassiagian.wordpress.com
+628175471005
[/]

**Comment by kasbah** [comment]
Yep!

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/squaresolid/fish-caller/

**Comment by squaresolid** [comment]
great! thank you!

:a
[][][]
andreas siagian
lifepatch - citizen initiative in art, science and technology
+628175471005
http://andreassiagian.wordpress.com
http://lifepatch.org | http://urbancult.net
[/][/][/]

**Pull request merged**
