### PR TITLE
ULX3S FPGA

### PR DESCRIPTION
**Pull request by emard**
Please add ULX3S FPGA R&D board

### CODE REVIEW

**Comment by kasbah** [comment]
Wow, that looks really cool. Do you have any part number for the BOM? You could try and use https://bom-builder.kitspace.org if it helps.

**Comment by emard** [comment]
Thnx! In my schematics and this bom are part numbers and
mouser order PN's
They have been exported in file 1-click-bom.tsv by
1-click-bom script

I see PN's in this tsv, I don't know why is the website
not autodetecting them

**Comment by kasbah** [comment]
Ah, I see, the `Distributor1_PN` and `MFG_PN` are not yet understood. [Here](https://github.com/monostable/1clickBOM#field-matching) is a list of all the known heading aliases. We can add them but it will take a bit longer to pull in the changes to kitspace than to change the BOM for now.

**Comment by emard** [comment]
Such field markings are in my schematics, I was using
KIBOM before

I need to rethink and make some script that will
automatically change field names

**Comment by kasbah** [comment]
Alternative would be to add support in
https://github.com/monostable/npm-1-click-bom

Would be awesome to support the default kibom output.

**Comment by emard** [comment]
Let me try to change MFG_PN to MPN
and Distributor1_PN to Mouser
with some script against kicad files
and see what result can we get then

**Comment by kasbah** [comment]
Preview is being put up here though I still need to manually re-trigger if anything changes. 

http://add-ulx3s.preview.kitspace.org/boards/github.com/emard/ulx3s/

**Comment by emard** [comment]
Fields are renamed, BOM looks better now check it out now!

There are some jumpers which have known part number
but should not be soldered, their fields are EMPTY_PN
don't let them go in

**Comment by emard** [comment]
If possible I'd like PCBWAY is removed from choice list of
producers of ULX3S board.

I paid them for 12 prototype 1609$, they produced me boards
with holes displaced (break out visually 180 degrees maybe a bit more)
probably it falls out of any IPC CLASS even CLASS 1
but they claim the junk they produced is CLASS 2 compliant and
don't want to re-produce boards at their cost. I'm trying to get
money back but I guess they will resist...

PCBCART offers CLASS 3 quality production with lower total cost than
PCBWAY

**Comment by emard** [comment]
Maybe if you can also change board color to RED with WHITE silkscreen...

**Comment by kasbah** [comment]
Yeah, looks great. Is it me or were there more Mouser parts before? 

If you want to add the color you have to add a `kitspace.yaml` with the text:

```yaml
color: red
```

You can also link to a `site` and change the `summary` from your GitHub one if you want. 

I can't remove any PCB services easily at the moment. The deal with the PCB links is that the services pay 10% commission on any sales referred. Any PCB manufacturer that agrees to that will be added so if PCBCART agree to this they can be added to. 

In the future I hope to pass some of this on the project designers (once Kitspace development is funded).  Let me know if you are still happy for it to be added and I'll merge. The page will still update every 24 hours after that.

**Comment by kasbah** [comment]
I don't think the attachments get forwarded by GitHub? Either way, are you ok with it being put up for now even with the PCBWay link?

**Comment by emard** [comment]
HI

OK I wish PCBWAY all the best and currently it's low probability that
anybody will order aseembly of ULX3S out of the blue so link can stay.
Maybe to note that IPC CLASS 3 is needed. PCBWAY dont have it.

As soon as possible add PCBCART they feature CLASS 3

**Comment by emard** [comment]
HI

It looks great at your site.

Could you maybe resync my git repository, I updated readme
about production, manufacturers and quality.

There are some of my experience with PCBWAY as it was with
ULX3S project. Something they did very good something not so,
hopfully the truth is not being too harsh for them.

**Comment by emard** [comment]
BOM question:

Some parts are in the BOM but should not be installed
how to specify for them to not appear in 1-click-bom list?

I currently mark them filed with Note: Do not install
and set part number in field EMPTY_PN
But is there a better way?

for example there can be solder pads for 2 voltage selection jumpers but
only one jumper should be installed at a time.

**Comment by emard** [comment]
In the meantime I have added most Digikey part numbers,
can you sync again, I'd like to see how does it work

**Comment by kasbah** [comment]
I'll re trigger, it may be easier for you to work with kitspace.org/submit
for now. I can't look at the BOM details right now as I am on mobile. The
BOM is all the parts people need to buy, no matter if they are placed or
not. When we add placement info support it will be a bit different.

**Comment by emard** [comment]
HI

It looks great now, mouser prices have dropped from 80$ to 70$
while digikey is still at 112$. Easy to compare with just a click

There are few minor errors in Digikey PN's this I can fix with
submit preview

kitspace.org is great

**Comment by emard** [comment]
HI

I made a bit of update, please resync when suitable

Can you also display "Note" field, in the BOM - it's a kind of
comment for the parts that don't go on board - I use it this way
when I don't want e.g R56 to be soldered on PCB:

References: R56
Note: Leave empty

**Comment by kasbah** [comment]
Re-triggered. What's in the BOM so far is just fields required to buy the parts, it's very focused that way. We could think about how to best integrate "do not place" / "do not fit" designator somehow as it has been [requested before](https://github.com/monostable/1clickBOM/issues/2) but I have been very hesitant to add any extra columns especially if they are not for the direct purpose of describing what parts to buy. 

As we expand the BOM to help more with the assembly side we can try and expand the fields but I am not sure a general purpose "note" is the way to go. In web terms the BOM takes up _a lot_ of space so we shouldn't add columns that are not useful to everyone.

**Comment by emard** [comment]
HI

BOM looks mostly OK good now. I have multiple alternative PN's
so I need different MPN columns
which are pin compatible but have different price and function,
it is shown OK

In kicad I have "Description" and "Value" fields but they are not passed
to file 1-click-bom.tsv - is that OK?

For production, In the gerbers zip there is missing "centroid" files,
a list of XY
coordinates and rotation for each part for automatic insertion
machine, this is it:
ulx3s-bottom.txt, ulx3s-top.txt

### Module positions - created on Wed May 23 15:33:31 2018 ###
### Printed by Pcbnew version kicad 5.0.0-rc2-dev-unknown+dfsg1+20180318-2
## Unit = inches, Angle = deg.
## Side : bottom
# Ref     Val                 Package
         PosX       PosY       Rot  Side
BAT1      CR1225              Keystone_3000_1x12mm-CoinCell
       2.7750     0.2500  180.0000  bottom
C1        22uF                C_0805_2012Metric
       0.2750     1.0750  270.0000  bottom

**Comment by kasbah** [comment]
You can have multiple MPN columns, that's no problem. You can only have one column for each retailer right now though. 

Regarding Gerbers I think it's fallen back to the fail-safe which is to have a guess at the Gerber based on folder has the most matches with [whats-that-gerber](https://github.com/tracespace/whats-that-gerber). If you tell it which folder to use in the kitspace.yaml I think it will include everything: `gerbers: path/to/folder`.

**Comment by emard** [comment]
I added
gerbers: plot
to kitspace.yaml control file

In the plot directory there are some unix symlinks, I'm not sure what
will ZIP do with them
or should I move them to another place

**Comment by kasbah** [comment]
Hmm, [looks the same actually](https://kitspace.org/boards/github.com/emard/ulx3s/ulx3s-34816dc-gerbers.zip). Did you mean to point it at `gerbers: plot/ulx3s`? 

> In kicad I have "Description" and "Value" fields but they are not passed to file 1-click-bom.tsv - is that OK?

"Description" should be included, "Value" field currently won't be. The convention I have been trying to push people towards is to put values into the description field since both people and machines can parse that (for machine parsing you can use [electro-grammar](https://github.com/monostable/electro-grammar)). I am still willing to be convinced to do it differently since it does put a lot of complexity into parsing the descriptions but it's not really a priority since electro-grammar is useful for a lot of stuff.

**Comment by kasbah** [comment]
So I just noticed that for the gerber files it will filter out anything that's not matched i.e. seen as a possible drawing by whats-that-gerber. I just opened up #136 to address this.

**Comment by emard** [comment]
"Description" is default field in kicad, I can't influence it and it contains
some junk text coming from generic footprint information, there's
no particular info related to the part, so e.g. 22nF or 10k will have
same "Description" field if both use same footprint 0805 for example
so we have "entropy" field there...

plot/ulx3s is a collection of symlinks that actually eases making zip
of  renamed gerber
files according to some manufacturer, e.g. seeedstudio wants gerbers named
as is in plot/seeedstudio, plot/ulx3s is something generic naming what all PCBA
so far accepted.

Direct output of kicad gerbers drill and placement is actually plot/
and there is
"fabrication output" file, this is ulx3s-bottom.txt and ulx3s-top.txt
which contain
XY coortdinates and rotation of the parts from tape and reel to actual
board position,
very important for every PCB assembly process

**Comment by emard** [comment]
HI

It's me again, just a resync please...

**Comment by emard** [comment]
HI

This workflow looks great, I can re-submit the same project and it
gets updated :)

I'd ask about digikey, the web plugin repots cannot add 3 of 53 lines
Does digikey limit us to 50 BOM lines or I have some syntax errors in BOM?

**Comment by kasbah** [comment]
> This workflow looks great, I can re-submit the same project and it gets updated :) 

Not sure what you mean, are you joking? :smile:  [The plan](https://github.com/monostable/kitspace#planned) is to much improve this workflow by integrating GitLab in the back-end which will allow easier project management, easier sync with Git repos but also direct file uploads so people don't have to use Git.

There is definitely something going wrong with the extension with Digikey and this BOM. If you uninstall the extension and use the direct Digikey link it only complains about one part out of 53: 1276-2904-1-ND. (Which it doesn't want to back-order when added like this for some reason -- doesn't really make sense either because you can still add it from the product page). Will have to have a close look at what's going on with the extension.

**Comment by emard** [comment]
Not joking, it's ok, in few iterations I have practically completely
polished it completely.
It's not a big deal to re-submit project and within less than 24h it
gets updated online

so at a click the same BOM is submitted to 2 different distributors
and immediately
one can see parts cost at the market. It was much more complex before and your
kitspace project helped me to make it all compatible

I will replace other alternative to the problematic part 1276-2904-1-ND

**Comment by kasbah** [comment]
Btw. the `MFG1_URL` is now confusing it so the part info (which you  get when you hover over an MPN in the BOM) isn't working .

**Comment by emard** [comment]
MFG1_URL is manufacturer name
I like it be form of URL.

What do you suggest me to use

It's handy for me to use short names
MNF1, MNF2

Or less practical:
Manufacturer1
Manufacturer2

**Comment by kasbah** [comment]
It just won't understand it in the form of a URL. If you leave it out or if
you use just the name then it can show you a lot of information from
octopart on each part.

**Comment by emard** [comment]
Can U Give me example which would work ?
Is this good enough?

MFG1: Diodes Incorporated
MFG1_URL: www.diodes.com
MPN1: 789331
MFG2: On semiconductor
MFG2_URL: www.on-semi.com
MPN2: 1234512

**Comment by kasbah** [comment]
I re-triggered it.

I am not sure how it will behave with those headings since they will both
match "manufacturer". It will probably depend on the order of them. You can
see how it will be handled by copying into and out of the extension from a
spreadsheet program. That uses the same parser.

There isn't enough space for adding these details to the table itself which
is why we have the popup. Mouser and digikey interfaces can be overwhelming
with details sometimes. A question of style I guess but I much prefer to
have a clean and minimal style with details that than can be uncovered by
the user if they want them.

**Comment by emard** [comment]
HI

I will try the submit preview and alphabetically reorder them to try
what works and the re-submit

**Comment by kasbah** [comment]
Done, I think it finds those chips fine it just doesn't have that much info on them and no images.

**Comment by kasbah** [comment]
Wait a minute, [Octopart thinks the FPGA is a laser driver?](https://octopart.com/search?q=LFE5U-85F-6BG381C).

**Comment by emard** [comment]
:) yes that's octopart thinks about FPGA is laser driver and look what
it thinks of
Micron SDRAM - some nonsense too :)))

**Comment by emard** [comment]
HI

There may be small bug in mouser plugin. Not big deal
but this is how it appears:

I have different symbols and footprints which should receive same
MPN soldered. Because they are somehow different, then in the BOM they
separate like this instead of merge into one

RD9, RD51, RD52 RC0805JR-070RL
RP1, RP2, RP3 RC0805JR-070RL

Mouser shows correct number of parts (6) but only lists
3 references (forgets to mention RD9, RD51, RD52)
RP1, RP2, RP3

Digikey is ok, it shows 2 separate BOM lines with correct
references, both having same PN

**Comment by kasbah** [comment]
Thanks for reporting those details. Unfortunately that seems to be an issue with the Mouser site. In 1-click BOM we automate https://www.mouser.co.uk/cart/ezbuy and that has the same problem.

**Comment by kasbah** [comment]
Out of interest, why do you want to keep these as separate lines in your BOM?

**Comment by emard** [comment]
This is a "difficult" question. Original shematics contains 4 schottky
diodes but they are expensive and 3 of them can be replaced with 0-ohm
resistors saving 1$ cost without much loss of functionality.

So to the diode symbol is associated resistor part number,
although I renamed diodes to start with "R" still BOM generator
separates the lines from the jumpers which are real 0-ohm resistors
and we have this situation of same PN appearing on 2 BOM lines...

**Comment by kasbah** [comment]
Your top copper seems to have disappeared. I reported this as https://github.com/mcous/gerber-parser/issues/25.

**Comment by emard** [comment]
Thanx I haven't noticed this!
Let him backup this as non-working  example.
I need to update copper layers but it's not yet release-ready

**Comment by kasbah** [comment]
I made a copy of the file that I linked in the gerber-parser issue so no
problem there.

**Comment by emard** [comment]
HI

kitspace buttons Mouser/Digikey are really handy to send 1-click BOM
directly to distributor. I'd like to know if it is (easily/already) possible to
add such buttons to my PCB github  page.

I'd like to click on the button and that some script automatically sends
up-to-date  BOM to mouser. If github can host such feature, I won't
mind if I can link
to kitspace with some http post/get link

Davor

**Comment by kasbah** [comment]
It's not currently possible no. For Digikey you can send a post request similar to what kitspace does when there is no 1-click BOM installed: 

https://github.com/monostable/kitspace/blob/4110aa5b6855aa1e4005fe1f7ac3ef3c0b454e86/src/buy_parts/direct_stores.jsx#L73-L83

It would require having a form though which you can't have in your readme. For Mouser it's even more complicated, see #63. 

You _can_ load the BOM into 1-click-BOM by visiting the `.tsv` on GitHub and using the [blue button](https://github.com/monostable/1clickBOM#loading-an-online-bom) but people already need to have 1-click BOM installed. I would suggest you add a link to the Kitspace page to your readme at least as that's the most straight forward way to buy the parts for now.

**Comment by emard** [comment]
HI

I see, github doesn't accept forms in readme. I will link to kitspace from
readme and occassionally submit update request. I had some changes
recently, clicked submit project at kitspace and it got updated very fast :)

Davor

**Comment by emard** [comment]
Aha :) - this detail I didn't know:
So I don't have to re-submit my project from kitspace page every time.
I just need to push changes in the git of the PCB project,
wait after some time (cca 1 day, sometimes less) and it will
"automatically" be updated on kitspace ?

**Comment by emard** [comment]
HI

Is there some chance that kitspace supports LCSC supplier?
Wide number of products, VERY low prices

https://lcsc.com/

**Comment by kasbah** [comment]
Will take a look at how difficult it would be when I get a chance.

>

**Comment by kasbah** [comment]
Haven't had a chance to look at this but added it [to the issue here](https://github.com/kitspace/kitspace/pull/135). If you wanted to have a look yourself it requires adding a lcsc.js in 1-click BOM similar to the [rapid.js I added recently](https://github.com/kitspace/1clickBOM/blob/b204fa59a621064479d34ea51d2ed16d2c6b3066/src/common/js/rapid.js) (not released yet).

**Comment by emard** [comment]
HI

Thanks for the issues added, it's not urgent, and I'm not very
crafty with javascript but I can take a look. I must also try to
order from LCSC and try if different but pin-compatible parts
work on my board

**Comment by emard** [comment]
HI

1-click-bom generated for Mouser in recent kitspace seems broken for
some fields, showing some error report like

More Than 1 Match Found for 25.12 Select from a list of matching products

strange seems it tries to tread floating point value 25.12 as part number or
something.... Do I need to upgrade 1-click-bom kicad script or something

**Comment by kasbah** [comment]
Hey emard, just looked into this. 

I recently upgraded the BOM parser to a dev version but I am not sure if I can call this a regression or not. Your BOM isn't really in a format I expected and it's more a coincidence that it sort of worked before. For multiple manufacturers and MPNS the parser expects them to follow each other like this `Manufacturer1 | MPN1 | Manufacturer2 | MPN2 | Manufacturer3 | MPN3 | ...`. You also have a lot of extra fields in your BOM that are getting picked up as something else, then being overwritten, etc. 

I could downgrade the BOM parser to fix this but it feels like a step back. I would suggest you reduce the 1-click-bom.tsv to only the info the Kitspace uses for now. What script are you using for the export?

**Comment by kasbah** [comment]
FYI: you can still load this BOM into the 1-click BOM extension (using the blue arrow, or copy/paste) and it will work as before, I haven't upgraded the parser there yet.

**Comment by kasbah** [comment]
It still doesn't seem like it will work. You can test it out on https://bom-builder.kitspace.org where the parser is upgraded. 

Where is the script to generate the BOM?

**Comment by kasbah** [comment]
I found the issue: you have `Mouser_URL` and `price100_Mouser` columns which are being parsed as Mouser part columns and then overwriting the previous fields.

**Comment by emard** [comment]
Aiieee I need such fields to keep track of some prices and
URLs, maybe not exactily mousers but also others

Is there some way out if?

**Comment by kasbah** [comment]
I think the best way forward for now is to have separate generated BOMs: one for Kitspace with just the essential info and one for yourself with all the extra info that Kitspace doesn't understand. 

As I develop Kitspace/BOM builder the issue should go away.

**Comment by emard** [comment]
I already use 1-clock-bom only for kitspace, for others I use kibom.

can U just point me how/what script controls which fields will be go
out to the file for kitspace

**Comment by kasbah** [comment]
In that case you should amend your script to just export the necessary fields. 

We use [these aliases to find the retailers/headings](https://github.com/kitspace/npm-1-click-bom/blob/ae579c2dd425d3c2041a0f4ed933fde1350a3228/src/parser.js#L7-L76). They are used as (case insensitive) regular expressions using this [lookup function](https://github.com/kitspace/npm-1-click-bom/blob/ae579c2dd425d3c2041a0f4ed933fde1350a3228/src/parser.js#L286-L296).

**Comment by kasbah** [comment]
Do you want some help with it? Maybe I could write a better export script. Are you using [this one](https://github.com/kitspace/1clickBOM/blob/0c078ef46f9a7c5710ff6718f30ceb41f7400ed1/output_scripts/kicad/1-click-bom_fields.py)?

**Comment by emard** [comment]
I'm busy with other things so I'd appreciate any help to get it working.
Seems I've been using slightly different one from here:
https://github.com/monostable/1clickBOM

So should I change to:
https://github.com/kitspace/1clickBOM

**Comment by kasbah** [comment]
No no, that's the same. The scripts haven't changed in 2 years, I just moved the repo. I'll take a look at making it better for cases like yours.

**Comment by emard** [comment]
Yes, I'm willing to try new stuff!

**Comment by emard** [comment]
HI i tried to remove fields "Mouser_URL"
from the 1clickBOM scripts to not be generated
but it still generates them, maybe this is not the right place?

partfields -= set( ['Reference', 'Value', 'Datasheet', 'Footprint',
'Mouser_URL', 'price100_Mouser'] )

**Comment by kasbah** [comment]
[Here is an amended script](https://cloud.monostable.co.uk/1-click-bom_fields_ignore.py) that ignores all the URL and price columns. 

```diff
diff --git a/output_scripts/kicad/1-click-bom_fields.py b/output_scripts/kicad/1-click-bom_fields.py
index cd0d5a0..f1eab4c 100644
--- a/output_scripts/kicad/1-click-bom_fields.py
+++ b/output_scripts/kicad/1-click-bom_fields.py
@@ -9,6 +9,7 @@ import kicad_netlist_reader
 import csv
 import sys
 import os
+import re
 
 def myEqu(self, other):
     """myEqu is a more advanced equivalence function for components which is
@@ -65,6 +66,9 @@ partfields -= set( ['Reference', 'Value', 'Datasheet', 'Footprint'] )
 
 columnset = compfields | partfields     # union
 
+
+ignore_columns = re.compile('[A-z0-9]*_URL|price')
+columnset = [c for c in columnset if ignore_columns.match(c) is None]
 # prepend an initial 'hard coded' list and put the enchillada into list 'columns'
 columns = ['References', 'Qty'] + sorted(list(columnset))
```

**Comment by emard** [comment]
HI

thanx, I applied this patch, regenerated 1-click bom and pushed
new one to my git

**Comment by emard** [comment]
HI

I updated latest ulx3s with BOM refreshed using kitspace 1clickbom
but now mouser is quite broken, can you take a look what happens??

**Comment by kasbah** [comment]
Looks like it's a continuation of the problems we observed above. The prices and URLs are being mixed into the Mouser stock number field. Are you sure you are using the amended export script?

image

**Comment by emard** [comment]
Hmm so I have to use special script for exporting...
hmmm I must it dig out from some mail logs

**Pull request merged**
